let shopItemsData = [
  {
    id: 1,
    name: "Ladies Coat",
    price: 10999,
    desc: "Coat with a hood, made of high-quality material",
    img: "images/jacket1.jpg",
  },
  {
    id: 2,
    name: "Boys Jacket",
    price: 9499,
    desc: "Jacket with a hood,available in black and blue colors.",
    img: "images/jacket2.jpg",
  },
  {
    id: 3,
    name: "Summer coat",
    price: 5149,
    desc: "High-quality wireless headphones with over-ear",
    img: "images/jacket3.jpg",
  },
  {
    id: 4,
    name: "Jacket",
    price: 5999,
    desc: "Stylish leather Jacket",
    img: "images/jacket4.jpg",
  },
  {
    id: 5,
    name: "Jeans shirt",
    price: 4149,
    desc: "Spring t-shirt with reasonable price",
    img: "images/jeans1.jpg",
  },
  {
    id: 6,
    name: "Jeans pant",
    price: 9199,
    desc: "Jeans pant for boys in summer season",
    img: "images/jeans2.jpg",
  },
  {
    id: 7,
    name: "Jeans pant",
    price: 9190,
    desc: "Jeans pant for boys in summer season",
    img: "images/jeans3.jpg",
  },
  {
    id: 8,
    name: "Girls Jeans",
    price: 19190,
    desc: "Jeans pant for boys in summer season",
    img: "images/jeans4.jpg",
  },
  {
    id: 9,
    name: "Summer shirt",
    price: 19190,
    desc: "Best for summer season",
    img: "images/shirt1.jpg",
  },
  {
    id: 10,
    name: "Summer shirt",
    price: 19190,
    desc: "Best for summer season",
    img: "images/shirt2.jpg",
  },
  {
    id: 11,
    name: "Stylish shirt",
    price: 19190,
    desc: "Best for summer season",
    img: "images/shirt3.jpg",
  },
  {
    id: 12,
    name: "White shirt",
    price: 19190,
    desc: "Shirt for spring and summer season",
    img: "images/shirt4.jpg",
  },
  {
    id: 13,
    name: "yellow shirt",
    price: 19190,
    desc: "Shirt for spring and summer season",
    img: "images/shirt5.jpg",
  },
  {
    id: 14,
    name: "Vest",
    price: 1910,
    desc: "Comfortable vest for summer season",
    img: "images/vest2.jpg",
  },
  {
    id: 15,
    name: "Vest",
    price: 9190,
    desc: "Jeans pant for boys in summer season",
    img: "images/vest1.jpg",
  },
];
